# Generated by Django 4.2.6 on 2023-10-19 20:50

import autogen.agentchat.assistant_agent
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManageBulletinBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Towncenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "coords",
                    models.JSONField(default=list, verbose_name="Spatial Coordinates"),
                ),
                ("population", models.PositiveIntegerField()),
                ("area", models.FloatField()),
                ("established_date", models.DateField()),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TowncenterAgent",
            fields=[
                ("agent_id", models.UUIDField(primary_key=True, serialize=False)),
                ("age", models.PositiveIntegerField()),
                ("clearance", models.JSONField(default=dict)),
                ("bank_balance", models.FloatField(default=0.0)),
            ],
            options={
                "abstract": False,
            },
            bases=(autogen.agentchat.assistant_agent.AssistantAgent, models.Model),
        ),
    ]
