# Generated by Django 4.2.6 on 2023-10-21 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Library", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "room_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_conversation",
                        to="Library.conversation",
                    ),
                ),
                ("participants", models.ManyToManyField(to="Library.conversation")),
            ],
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
    ]
